# version: "3.8" ### **IMPORTANT NOTE**: Do not alter this line for any reason

services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: LibreChat-NGINX
    ports:
      - "80:80"
      - "443:443" # Enable HTTPS
    depends_on:
      - api
    restart: always
    volumes:
      # Correctly mount the main Nginx configuration
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      
      # Mount the server-specific configuration
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      
      # Mount SSL certificates
      - ../nginx/ssl/self-signed.crt:/etc/nginx/ssl/self-signed.crt:ro
      - ../nginx/ssl/self-signed.key:/etc/nginx/ssl/self-signed.key:ro
    environment:
      # Optional: Define any environment variables if needed
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - librechat-network

networks:
  librechat-network:
    external: false